name: Upload Prebuilt WebView APK to Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  upload-prebuilt:
    runs-on: ubuntu-latest
    name: Upload Prebuilt APK

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if APK exists
        id: check_apk
        run: |
          APK_PATH="prebuilt/arm64/webview.apk"
          if [ ! -f "$APK_PATH" ]; then
            echo "❌ APK não encontrado em $APK_PATH"
            exit 1
          fi
          VERSION="prebuilt-$(date +%Y%m%d%H%M%S)"
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          name: WebView Prebuilt ${{ steps.check_apk.outputs.version }}
          tag_name: ${{ steps.check_apk.outputs.version }}
          files: ${{ steps.check_apk.outputs.apk_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}